### ISSUE TITLE
Create Thread Cards

### ISSUE THREAD

**Issue by SantosOMartinez** [uprm-inso-4116-2021-2022-s1/Team-F#3]
The Discover and Home Page require Cards that show a preview of each thread to join. 

Need to implement the thread cards that are found in [Figma](https://www.figma.com/file/aF7YN8MANfWsqWTwQY5g1V/App-Design?node-id=411%3A9267).

### TODO in src/common/components
- [ ] Create ThreadCard Folder.
- [ ] Add Thread.module.sass
- [ ] Add index.tsx
- [ ] Implement the basic card template for the component.
- [ ] Style the Component to look like the [Figma](https://www.figma.com/file/aF7YN8MANfWsqWTwQY5g1V/App-Design?node-id=411%3A9267) version.
